load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_pose_detection",
    calculators = ["//mediapipe/customgraphs/pose_tracking:pose_tracking_cpu_deps"],
)